---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
    run_list:
    - recipe[apt]
  - name: debian-8.5
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[t3-gitweb::default]
    attributes:
      gitweb:
        hostname: t3gitweb.vagrant
